# Generated by Django 4.1.13 on 2024-07-22 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_interest_volunteer_volunteerprojectmatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
